import { z } from 'zod'

const medicineItemSchema = z.object({
  name: z.string().min(1),
  dose: z.string().optional(),
  frequency: z.string().optional(),
  duration: z.string().optional(),
  notes: z.string().optional(),
})

export const createPrescriptionSchema = z
  .object({
    encounterId: z.string().min(1),
    historyTakingId: z.string().optional(),
    labReportsEntryId: z.string().optional(),
    medicine: z.array(medicineItemSchema).min(1).optional(),
    items: z.array(medicineItemSchema).min(1).optional(),
    labTests: z.array(z.string().min(1)).optional(),
    labNotes: z.string().optional(),
    diagnosticTests: z.array(z.string().min(1)).optional(),
    diagnosticNotes: z.string().optional(),
    therapyTests: z.array(z.string().min(1)).optional(),
    therapyNotes: z.string().optional(),
    diagnosticDiscount: z.string().optional(),
    therapyDiscount: z.string().optional(),
    counsellingDiscount: z.string().optional(),
    therapyPlan: z.any().optional(),
    therapyMachines: z.any().optional(),
    counselling: z.any().optional(),
    primaryComplaint: z.string().optional(),
    primaryComplaintHistory: z.string().optional(),
    familyHistory: z.string().optional(),
    treatmentHistory: z.string().optional(),
    allergyHistory: z.string().optional(),
    history: z.string().optional(),
    examFindings: z.string().optional(),
    diagnosis: z.string().optional(),
    advice: z.string().optional(),
    vitals: z
      .object({
        pulse: z.coerce.number().optional(),
        temperatureC: z.coerce.number().optional(),
        bloodPressureSys: z.coerce.number().optional(),
        bloodPressureDia: z.coerce.number().optional(),
        respiratoryRate: z.coerce.number().optional(),
        bloodSugar: z.coerce.number().optional(),
        weightKg: z.coerce.number().optional(),
        heightCm: z.coerce.number().optional(),
        bmi: z.coerce.number().optional(),
        bsa: z.coerce.number().optional(),
        spo2: z.coerce.number().optional(),
      })
      .partial()
      .optional(),
    historyEdits: z.object({
      personalInfo: z.any().optional(),
      maritalStatus: z.any().optional(),
      coitus: z.any().optional(),
      health: z.any().optional(),
      sexualHistory: z.any().optional(),
      previousMedicalHistory: z.any().optional(),
      arrivalReference: z.any().optional(),
    }).optional(),
    createdBy: z.string().optional(),
  })
  .refine((data) => Array.isArray((data as any).medicine) || Array.isArray((data as any).items), {
    message: 'Medicine is required',
    path: ['medicine'],
  })

export const updatePrescriptionSchema = z.object({
  historyTakingId: z.string().optional(),
  labReportsEntryId: z.string().optional(),
  medicine: z.array(medicineItemSchema).optional(),
  items: z.array(medicineItemSchema).optional(),
  labTests: z.array(z.string().min(1)).optional(),
  labNotes: z.string().optional(),
  diagnosticTests: z.array(z.string().min(1)).optional(),
  diagnosticNotes: z.string().optional(),
  therapyTests: z.array(z.string().min(1)).optional(),
  therapyNotes: z.string().optional(),
  diagnosticDiscount: z.string().optional(),
  therapyDiscount: z.string().optional(),
  counsellingDiscount: z.string().optional(),
  therapyPlan: z.any().optional(),
  therapyMachines: z.any().optional(),
  counselling: z.any().optional(),
  primaryComplaint: z.string().optional(),
  primaryComplaintHistory: z.string().optional(),
  familyHistory: z.string().optional(),
  treatmentHistory: z.string().optional(),
  allergyHistory: z.string().optional(),
  history: z.string().optional(),
  examFindings: z.string().optional(),
  diagnosis: z.string().optional(),
  advice: z.string().optional(),
  vitals: z.object({
    pulse: z.coerce.number().optional(),
    temperatureC: z.coerce.number().optional(),
    bloodPressureSys: z.coerce.number().optional(),
    bloodPressureDia: z.coerce.number().optional(),
    respiratoryRate: z.coerce.number().optional(),
    bloodSugar: z.coerce.number().optional(),
    weightKg: z.coerce.number().optional(),
    heightCm: z.coerce.number().optional(),
    bmi: z.coerce.number().optional(),
    bsa: z.coerce.number().optional(),
    spo2: z.coerce.number().optional(),
  }).partial().optional(),
  historyEdits: z.object({
    personalInfo: z.any().optional(),
    maritalStatus: z.any().optional(),
    coitus: z.any().optional(),
    health: z.any().optional(),
    sexualHistory: z.any().optional(),
    previousMedicalHistory: z.any().optional(),
    arrivalReference: z.any().optional(),
  }).optional(),
})
